"""P12 / FR-054: the customer-facing PR body — the only Patchline-authored
surface visible to customers. Brand-neutral (no Sneferu mention).

Provenance block is included ONLY when the engine supplies provenance
metadata; each present field renders independently; when all typed fields are
absent the body carries the minimal notice and nothing else.
"""
from __future__ import annotations

from typing import Optional

from ..adapters.engine import Provenance

MINIMAL_NOTICE = "This PR was generated by Patchline. Review the diff carefully before merging."

TRUST_NOTE = (
    "Note: after merging, Patchline verifies migration by rescanning for the old API pattern. "
    "A 'migrated' result means the old pattern was absent at scan time; it does not verify "
    "that this exact diff was applied verbatim."
)


def compose_pr_body(
    *,
    entry_title: str,
    summary: Optional[str],
    provenance: Optional[Provenance],
    scan_link: Optional[str] = None,
) -> str:
    lines = [f"## {entry_title}", ""]
    if summary:
        lines += [summary, ""]

    rendered_provenance = []
    if provenance is not None:
        if provenance.quality_score is not None:
            rendered_provenance.append(f"- Quality score: {provenance.quality_score}")
        if provenance.certificate_class:
            rendered_provenance.append(f"- Certificate class: {provenance.certificate_class}")
        if provenance.disagreement_record:
            rendered_provenance.append(f"- Disagreement record: {provenance.disagreement_record}")
        if provenance.models:
            rendered_provenance.append(f"- Models involved: {', '.join(provenance.models)}")
    if rendered_provenance:
        lines += ["### Provenance", *rendered_provenance, ""]

    lines.append(TRUST_NOTE)
    lines.append("")
    if scan_link:
        lines.append(f"Patchline scan: {scan_link}")
        lines.append("")
    lines.append(f"_{MINIMAL_NOTICE}_")
    return "\n".join(lines)


def body_has_only_minimal_notice(body: str) -> bool:
    """True when no provenance fields rendered (FR-054 minimal case)."""
    return "Quality score" not in body and "Certificate class" not in body and "Disagreement record" not in body
